pragma solidity ^0.8.0;

// SPDX-License-Identifier: MIT

/*
 * $name$
 *
 * $param.description$
 *
 * Author: $param.author_name$
 *
 * Generated by https://chainbox.id
 *
 */

import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "./HasAdmin.sol";


contract $name_pascal_case$ is
    ERC721,
    Ownable,
    HasAdmin
{
    using Counters for Counters.Counter;

    // <% if param.with_max_supply %>
    uint256 public constant maxSupply = $param.max_supply$;
    // <% endif %>

    Counters.Counter private _idGen;

    string public baseTokenURI;

    event ItemMinted(uint256 indexed tokenId);

    constructor(string memory _baseTokenURI, address owner, address admin)
        ERC721("$name$", "$param.token_code$")
    {
        baseTokenURI = _baseTokenURI;

        transferOwnership(owner);
        _setAdmin(admin);
        _idGen.reset();
    }

    modifier onlyAdminOrOwner() {
        require(
            _isAdmin(_msgSender()) || owner() == _msgSender(),
            "Only owner or admin can set daily aging rate"
        );
        _;
    }

    function changeAdmin(address newAdmin) external onlyOwner {
        _setAdmin(newAdmin);
    }

    function mint(address to) external returns(uint256) {
        _idGen.increment();
        uint256 tokenId = _idGen.current();

        // <% if param.with_max_supply %>
        require(tokenId <= maxSupply, "max supply exceeded");
        // <% endif %>

        _safeMint(to, tokenId);

        emit ItemMinted(tokenId);

        return tokenId;
    }

    function totalSupply() external view returns(uint256) {
        return _idGen.current();
    }

    function _baseURI() internal view virtual override returns (string memory) {
        return baseTokenURI;
    }

    function setBaseURI(string memory baseURI) public onlyOwner {
        baseTokenURI = baseURI;
    }
}
