#!/usr/bin/python3
#
# Script to prepare the Arare contract for testing.
# 
# This script will copy original contract and modify some hard-coded specifications
# to make it suitable for testing.
#

import os
from shutil import copyfile

#from brownie import $name_pascal_case$

def main():
    test_file = "contracts/$name_pascal_case$Test.sol"
    copyfile("contracts/$name_pascal_case$.sol", test_file)
    
    lines = []
    with open(test_file, "r") as f:
        lines = f.readlines()

    with open(test_file, "w") as f:
        for line in lines:
            if "contract $name_pascal_case$ is" in line:
                f.write("// This contract cloned from the original contract for testing purpose\n")
                f.write("// not suitable for production.\n")
                f.write("//\n")
                f.write("// You don't suppose to edit this file.\n")
                f.write("// Please run: `brownie run scripts/test.py` to generate this file and run testings.\n\n")
                f.write(line.replace("contract $name_pascal_case$ is", "contract $name_pascal_case$Test is"))
            elif "uint256 public constant maxSupply" in line:
                f.write("    // autogenerated for testing\n")
                f.write("    uint256 public constant maxSupply = 10;\n")
            else:
                f.write(line)

    # run the tests
    os.system("brownie test")
